import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faEnvelope } from "@fortawesome/free-solid-svg-icons";

// const element = <FontAwesomeIcon icon={faEnvelope} />;

export const metadata = {
	title: "Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="nav">
					<Link href="/">
						<button>Home</button>
					</Link>
					<Link href="/posts">
						<button>Posts</button>
					</Link>
					<Link href="/articles">
						<button>Articles</button>
					</Link>
				</nav>
				{children}
				{/* <span
					style={{
						position: "fixed",
						right: "20px",
						bottom: "20px",
						background: "teal",
						color: "white",
						padding: "7px 9px 5px",
						fontSize: "20px",
						fontWeight: "bold",
						borderRadius: "5px",
						cursor: "pointer",
						transition: "0.2s",
					}}
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						height="1em"
						viewBox="0 0 384 512"
					>
						<path d="M214.6 41.4c-12.5-12.5-32.8-12.5-45.3 0l-160 160c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 141.2V448c0 17.7 14.3 32 32 32s32-14.3 32-32V141.2L329.4 246.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-160-160z" />
					</svg>
				</span> */}
			</body>
		</html>
	);
}
